repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix]
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-annotations]
        files: ^(uk_threat_level)/
        exclude: (tests)
        args: [--max-line-length=120]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        files: ^(uk_threat_level)/
        exclude: (tests)
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        files: ^(uk_threat_level)/
        exclude: (tests)
