name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: pytest --cov-report xml:coverage.xml
      - name: Comment Coverage PR
        uses: orgoro/coverage@v3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          coverageFile: coverage.xml
